# This file was generated by GoReleaser. DO NOT EDIT.
cask "switchboard" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "2849cf44d47775131d1485d19fe580f523f6b3fa8462399f4b95e9963d1c9632"
      url "https://github.com/alsey89/switchboard/releases/download/v#{version}/switchboard_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "29e0d1731df780997c0a4b4271c726233c2bbab0ca012dfdc60357676a1bcbd5"
      url "https://github.com/alsey89/switchboard/releases/download/v#{version}/switchboard_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3a6d24d80640c1e9a2879989da9e77a63d701782d9ba79a65b4573d1de2887de"
      url "https://github.com/alsey89/switchboard/releases/download/v#{version}/switchboard_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c3dfff7ed1842b60396e833401c78884257fde29204c1ec0a5d2e884ff724f4a"
      url "https://github.com/alsey89/switchboard/releases/download/v#{version}/switchboard_#{version}_linux_arm64.tar.gz"
    end
  end

  name "switchboard"
  desc "Local domains with real HTTPS for web development"
  homepage "https://github.com/alsey89/switchboard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "switchboard"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/switchboard"]
    end
  end

  zap launchctl: [
      "io.github.alsey89.switchboard",
    ]

  caveats <<~EOS
    Set up once:

      switchboard setup

    That creates the local CA, points the OS resolver at Switchboard,
    trusts the CA in your login keychain, and installs the background
    service. Every step that needs your password prints the exact command
    first.

    Then:

      switchboard add app 3000  &&  open https://app.test

    It asks for a password because :443 and :80 are reserved for root on
    macOS. Switchboard installs a small parent process that binds those two
    sockets and immediately drops to your user. The proxy, the TLS stack
    and the local CA all run as you, never as root.

    Prefer nothing privileged at all? Put this in
    ~/.config/switchboard/config.toml before running setup:

      http_port  = 8080
      https_port = 8443

    You get a plain user agent instead. Everything works the same, and
    URLs carry the port (https://app.test:8443).

    To remove everything, including the privileged launch daemon:

      switchboard uninstall

    Run that before `brew uninstall`. Homebrew cannot remove the privileged
    parts on its own.
  EOS
end
